# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # 行末の不要な空白を削除
      - id: end-of-file-fixer # ファイル末尾に空行を確保
      - id: check-yaml # YAMLファイルの構文チェック
      - id: check-yaml # YAMLファイルの構文チェック
      - id: check-json # JSONファイルの構文チェック
      - id: check-added-large-files # 大きすぎるファイルが追加されるのを防ぐ

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^src/backend/ # バックエンドのPythonファイルのみ対象

  # - repo: https://github.com/pycqa/isort # Temporarily disabled to rely on black for import sorting
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       files: ^src/backend/ # バックエンドのPythonファイルのみ対象

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=127", "--max-complexity=10"] # CIと同じ設定
        files: ^src/backend/ # バックエンドのPythonファイルのみ対象

  # Prettier (using mirror repository)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use a specific version compatible with your Prettier setup if needed
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|html|json|md|yaml)$ # 対象ファイルを指定
        # args: ['--config', './.prettierrc.json'] # If you have a prettier config file

  # ESLint (using local installation via npx)
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix # ローカルのeslintを実行
        language: node
        files: \.[jt]sx?$ # .js, .jsx, .ts, .tsx ファイルを対象
        pass_filenames: true # ファイル名を引数として渡す
        # types: [javascript] # 必要に応じて
